apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Github\mindy-project\core-docker\docker\kubernetes\kompose.exe -f ../docker-compose.core.yml -f ../docker-compose.ai.yml -f ../docker-compose.blog.yml -f ../docker-compose.development.yml -f ../docker-compose.ecommerce.yml -f ../docker-compose.mail.yml -f ../docker-compose.s3.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    service: analytics
  name: analytics
spec:
  replicas: {{ int .Values.core.analytics.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      service: analytics
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Github\mindy-project\core-docker\docker\kubernetes\kompose.exe -f ../docker-compose.core.yml -f ../docker-compose.ai.yml -f ../docker-compose.blog.yml -f ../docker-compose.development.yml -f ../docker-compose.ecommerce.yml -f ../docker-compose.mail.yml -f ../docker-compose.s3.yml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        service: analytics
    spec:
      hostAliases:
        - ip: 127.0.0.1
          hostnames:
            - {{ .Values.core.analytics.logflareHost | quote }}
      initContainers:
        - name: init-analytics
          image: supabase/postgres:15.8.1.085
          command:
            - sh
            - -c
            - |
              until pg_isready -h db -p 5432 -U postgres; do echo waiting for postgres; sleep 2; done
      containers:
        - env:
            - name: DB_DATABASE
              value: _supabase
            - name: DB_SCHEMA
              value: _analytics
            - name: DB_USERNAME
              value: supabase_admin
            - name: LOGFLARE_FEATURE_FLAG_OVERRIDE
              value: multibackend=true
            - name: LOGFLARE_MIN_CLUSTER_SIZE
              value: "1"
            - name: LOGFLARE_SINGLE_TENANT
              value: "true"
            - name: LOGFLARE_SUPABASE_MODE
              value: "true"
            - name: POSTGRES_BACKEND_SCHEMA
              value: _analytics
            - name: DB_PORT
              value: "5432"
            - name: LOGFLARE_NODE_HOST
              value: "127.0.0.1"
            - name: PHX_URL_HOST
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: NGINX_LOGFLARE_HOST_URL
            - name: DB_HOSTNAME
              value: db
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: POSTGRES_PASSWORD
            - name: LOGFLARE_PUBLIC_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: LOGFLARE_PUBLIC_ACCESS_TOKEN
            - name: LOGFLARE_PRIVATE_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: LOGFLARE_PRIVATE_ACCESS_TOKEN
            - name: POSTGRES_BACKEND_URL
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: ANALYTICS_POSTGRES_BACKEND_URL
          image: supabase/logflare:1.45.6
          resources:
            requests:
              memory: {{ .Values.core.analytics.memoryRequest }}
            limits:
              memory: {{ .Values.core.analytics.memoryLimit }}
          startupProbe:
            tcpSocket:
              port: 4000
            initialDelaySeconds: 30
            failureThreshold: 90
            periodSeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 4000
            failureThreshold: 60
            periodSeconds: 5
            timeoutSeconds: 5
          name: supabase-analytics
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
      restartPolicy: Always
