apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Github\mindy-project\core-docker\docker\kubernetes\kompose.exe -f ../docker-compose.core.yml -f ../docker-compose.ai.yml -f ../docker-compose.blog.yml -f ../docker-compose.development.yml -f ../docker-compose.ecommerce.yml -f ../docker-compose.mail.yml -f ../docker-compose.s3.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    service: realtime
  name: realtime
spec:
  strategy:
    type: Recreate
  replicas: {{ int .Values.core.realtime.replicas }}
  selector:
    matchLabels:
      service: realtime
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Github\mindy-project\core-docker\docker\kubernetes\kompose.exe -f ../docker-compose.core.yml -f ../docker-compose.ai.yml -f ../docker-compose.blog.yml -f ../docker-compose.development.yml -f ../docker-compose.ecommerce.yml -f ../docker-compose.mail.yml -f ../docker-compose.s3.yml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        service: realtime
    spec:
      initContainers:
        - name: init-realtime
          image: curlimages/curl
          command: ['sh', '-c', 'until curl -fsSL -m 2 db:5432 > /dev/null 2>&1 || [ $? -eq 52 ]; do echo waiting for postgres; sleep 2; done;']
      containers:
        - env:
            - name: APP_NAME
              value: realtime
            - name: DB_AFTER_CONNECT_QUERY
              value: 'SET search_path TO _realtime'
            - name: DB_ENC_KEY
              value: supabaserealtime
            - name: DB_USER
              value: supabase_admin
            - name: DNS_NODES
              value: "''"
            - name: ERL_AFLAGS
              value: -proto_dist inet_tcp
            - name: PORT
              value: "4000"
            - name: RLIMIT_NOFILE
              value: "10000"
            - name: SEED_SELF_HOST
              value: "true"
            - name: RUN_JANITOR
              value: "true"
            - name: DB_HOST
              value: db
            - name: DB_NAME
              value: postgres
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: POSTGRES_PORT
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: POSTGRES_PASSWORD
            - name: API_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: API_JWT_SECRET
            - name: ANON_KEY
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: ANON_KEY
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: SECRET_KEY_BASE
          image: supabase/realtime:v2.57.2
          startupProbe:
            tcpSocket:
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 36
            timeoutSeconds: 3
          readinessProbe:
            tcpSocket:
              port: 4000
            periodSeconds: 5
            failureThreshold: 6
            timeoutSeconds: 3
          livenessProbe:
            tcpSocket:
              port: 4000
            periodSeconds: 10
            failureThreshold: 6
            timeoutSeconds: 3
          name: supabase-realtime
          ports:
            - containerPort: 4000
      restartPolicy: Always
